/**:
  ros__parameters:
    laserMapping:
      cam_model: Pinhole
      cam_width: 720
      cam_height: 480
      scale: 1.0
      cam_fx: 298.81731033325195
      cam_fy: 98.81731033325195
      cam_cx: 360.0
      cam_cy: 240.0
      cam_d0: 0.0
      cam_d1: 0.0
      cam_d2: 0.0
      cam_d3: 0.0